name: CI

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "lib/**"
      - "*.gemspec"
      - "spec/**"
      - "Rakefile"
      - "Gemfile"
  pull_request:
    branches:
      - master
  create:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    continue-on-error: ${{matrix.ruby == 'head' || matrix.ruby == 'jruby' || matrix.ruby == 'truffleruby'}}
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - "3.2"
        - "3.1"
        - "3.0"
        - "2.7"
        - "2.6"
        - "2.5"
        - "2.4"
        - head
        - jruby
        - truffleruby
        include:
          - ruby: "3.2"
            coverage: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - name: Run all tests
        run: bundle exec rake spec
